import { useState } from 'react';
import { BookOpen, HelpCircle, List, Copy, Share2, CheckCircle, Home } from 'lucide-react';
import toast from 'react-hot-toast';

const NotesView = ({ note, onBack }) => {
  const [activeTab, setActiveTab] = useState('detailed'); // short | detailed | viva
  const { content } = note;

  // 1. Function to Convert Note to String (For Copy/Share)
  const formatNoteForShare = () => {
    let text = `🦷 *SUPER DENTAL NOTES*\n`;
    text += `📚 Subject: ${note.subject}\n`;
    text += `🏷️ Topic: ${content.title}\n\n`;

    if (content.short_notes?.length > 0) {
      text += `⚡ *QUICK REVISION*\n`;
      content.short_notes.forEach(p => text += `• ${p}\n`);
      text += `\n`;
    }

    if (content.mnemonics?.length > 0) {
      text += `🧠 *MNEMONICS*\n`;
      content.mnemonics.forEach(m => text += `👉 ${m}\n`);
      text += `\n`;
    }

    if (content.viva_questions?.length > 0) {
      text += `❓ *VIVA QUESTIONS*\n`;
      content.viva_questions.forEach(vq => text += `Q: ${vq.q}\nA: ${vq.a}\n\n`);
    }

    text += `(Generated by AI Dental Assistant 🤖)`;
    return text;
  };

  // 2. Handle Copy
  const handleCopyAll = () => {
    const text = formatNoteForShare();
    navigator.clipboard.writeText(text);
    toast.success("Full Note Copied! Ready to paste.");
  };

  // 3. Handle Share (Mobile Native Share)
  const handleShare = async () => {
    const text = formatNoteForShare();
    if (navigator.share) {
      try {
        await navigator.share({
          title: content.title,
          text: text,
        });
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      // Fallback for desktop
      handleCopyAll();
    }
  };

  // Helper to render lists
  const ListRenderer = ({ items }) => (
    <ul className="space-y-3">
      {items?.map((item, idx) => (
        <li key={idx} className="flex gap-3 text-gray-700 bg-white p-3 rounded-lg border border-gray-100 shadow-sm text-sm leading-relaxed">
          <span className="text-blue-500 font-bold mt-0.5">•</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );

  return (
    <div className="bg-gray-50 min-h-screen pb-32 relative">
      
      {/* --- HEADER --- */}
      <div className="bg-gradient-to-br from-blue-600 to-indigo-700 text-white p-6 pb-8 rounded-b-[2rem] shadow-xl relative overflow-hidden">
        {/* Decorative Circle */}
        <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full -mr-10 -mt-10 blur-xl"></div>
        
        <div className="relative z-10">
          <div className="flex justify-between items-start mb-2">
            <span className="text-[10px] uppercase tracking-wider font-bold bg-white/20 px-2 py-1 rounded-md backdrop-blur-sm">
              {note.subject}
            </span>
            <span className="flex items-center gap-1 text-[10px] font-bold bg-green-500/90 px-2 py-1 rounded-full shadow-sm">
              <CheckCircle size={12} /> Saved
            </span>
          </div>
          <h1 className="text-2xl font-bold leading-tight mt-2">{content.title}</h1>
          <p className="text-blue-100 text-xs mt-1">Generated via {note.mode === 'image' ? 'Image Analysis' : note.mode === 'pdf' ? 'PDF Extraction' : 'Topic Search'}</p>
        </div>
      </div>

      {/* --- TABS (Sticky) --- */}
      <div className="flex justify-around bg-white shadow-sm sticky top-0 z-20 mx-4 -mt-6 rounded-xl border border-gray-100">
        {[
          { id: 'short', label: 'Overview', icon: List },
          { id: 'detailed', label: 'Detailed', icon: BookOpen },
          { id: 'viva', label: 'Viva Q&A', icon: HelpCircle },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex-1 py-3 flex flex-col items-center text-xs font-semibold transition-all ${
              activeTab === tab.id 
                ? 'text-blue-600 bg-blue-50/50 rounded-xl' 
                : 'text-gray-400 hover:bg-gray-50'
            }`}
          >
            <tab.icon size={18} className="mb-1" />
            {tab.label}
          </button>
        ))}
      </div>

      {/* --- CONTENT AREA --- */}
      <div className="p-4 space-y-6 mt-2">
        
        {/* VIEW: DETAILED */}
        {activeTab === 'detailed' && (
          <div className="space-y-5 animate-in slide-in-from-bottom-4 duration-500">
            {Object.entries(content.detailed_notes).map(([key, value]) => {
               if(!value || (Array.isArray(value) && value.length === 0)) return null;
               
               return (
                <div key={key} className="bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden">
                  <div className="bg-indigo-50/50 px-5 py-3 border-b border-indigo-50 flex justify-between items-center">
                    <h3 className="font-bold text-indigo-900 uppercase text-xs tracking-wider">
                      {key.replace(/_/g, ' ')}
                    </h3>
                  </div>
                  <div className="p-5">
                    {Array.isArray(value) ? <ListRenderer items={value} /> : <p className="text-gray-700 text-sm leading-7">{value}</p>}
                  </div>
                </div>
              );
            })}
             
             {/* Tables */}
            {content.tables?.map((table, idx) => (
              <div key={idx} className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
                 <div className="bg-gray-800 text-white p-3 text-center font-bold text-sm">{table.title}</div>
                 <div className="overflow-x-auto">
                   <table className="w-full text-sm text-left">
                     <thead className="text-xs text-gray-500 uppercase bg-gray-50 border-b">
                       <tr>
                         {table.columns.map((col, cIdx) => <th key={cIdx} className="px-4 py-3 font-semibold whitespace-nowrap">{col}</th>)}
                       </tr>
                     </thead>
                     <tbody className="divide-y divide-gray-100">
                       {table.rows.map((row, rIdx) => (
                         <tr key={rIdx} className="bg-white hover:bg-gray-50">
                           {row.map((cell, cIdx) => <td key={cIdx} className="px-4 py-3 border-r border-gray-50 last:border-0 min-w-[120px]">{cell}</td>)}
                         </tr>
                       ))}
                     </tbody>
                   </table>
                 </div>
              </div>
            ))}
          </div>
        )}

        {/* VIEW: SHORT NOTES */}
        {activeTab === 'short' && (
           <div className="animate-in slide-in-from-bottom-4 duration-500 space-y-4">
             <div className="bg-gradient-to-br from-amber-50 to-orange-50 p-5 rounded-2xl border border-orange-100 shadow-sm">
               <h3 className="font-bold text-orange-800 mb-4 flex items-center gap-2">
                 ⚡ Quick Points
               </h3>
               <ListRenderer items={content.short_notes} />
             </div>
             
             {/* Mnemonics */}
             {content.mnemonics?.length > 0 && (
               <div className="bg-gradient-to-br from-emerald-50 to-green-50 p-5 rounded-2xl border border-green-100 shadow-sm">
                 <h3 className="font-bold text-green-800 mb-4 flex items-center gap-2">
                   🧠 Memory Tricks (Mnemonics)
                 </h3>
                 <ul className="space-y-2">
                   {content.mnemonics.map((m, i) => (
                     <li key={i} className="text-green-900 font-medium text-sm bg-white/60 p-3 rounded-lg border border-green-100 flex gap-2">
                       <span>💡</span> {m}
                     </li>
                   ))}
                 </ul>
               </div>
             )}
           </div>
        )}

        {/* VIEW: VIVA */}
        {activeTab === 'viva' && (
          <div className="space-y-4 animate-in slide-in-from-bottom-4 duration-500">
            {content.viva_questions?.map((item, idx) => (
              <div key={idx} className="bg-white p-5 rounded-2xl border border-gray-200 shadow-sm hover:shadow-md transition-shadow">
                <p className="font-bold text-gray-800 text-sm mb-3 flex gap-2">
                  <span className="text-red-500">Q.</span> {item.q}
                </p>
                <div className="text-gray-600 text-sm bg-gray-50 p-3 rounded-xl border border-gray-100 flex gap-2">
                  <span className="text-green-600 font-bold">A.</span>
                  {item.a}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* --- BOTTOM ACTION BAR (Samsung Style) --- */}
      <div className="fixed bottom-6 left-4 right-4 bg-white/90 backdrop-blur-md p-2 rounded-2xl shadow-2xl border border-gray-200 z-50 flex gap-2">
        {onBack && (
            <button 
                onClick={onBack}
                className="p-3 rounded-xl bg-gray-100 text-gray-600 hover:bg-gray-200"
            >
                <Home size={20} />
            </button>
        )}
        
        <button 
          onClick={handleCopyAll}
          className="flex-1 flex items-center justify-center gap-2 bg-gray-100 text-gray-800 font-bold py-3 rounded-xl active:scale-95 transition-transform"
        >
          <Copy size={18} /> Copy Text
        </button>
        
        <button 
          onClick={handleShare}
          className="flex-1 flex items-center justify-center gap-2 bg-blue-600 text-white font-bold py-3 rounded-xl shadow-lg shadow-blue-200 active:scale-95 transition-transform"
        >
          <Share2 size={18} /> Share
        </button>
      </div>

    </div>
  );
};

export default NotesView;